name: Lint

on:
  push:
    branches:
      - main
      - feat-lerna-bootstrap-deprecate
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14

    steps:
      - uses: actions/checkout@v3

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          ignore: "./**/CHANGELOG.md"
          args: "./**/*.md"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: |
            package.json
            detectors/node/*/package.json
            metapackages/*/package.json
            packages/*/package.json
            plugins/node/*/package.json
            plugins/web/*/package.json
            propagators/*/package.json

      - name: Bootstrap
        run: |
          npm install --only=dev --ignore-scripts
      - name: Lint
        run: npm run lint
