name: TAV for Push
on:
  push:
    branches:
      - "main"
      - "release/**"
      - "release-please/**"
      - feat-lerna-bootstrap-deprecate

jobs:
  tav:
    uses: ./.github/workflows/test-all-versions.yml
    with:
      lerna-args: ""
